#export.tcl: Tcl script for re-creating project E:/FPGA/pcie/pcie.pds
#Build: Fabric Compiler 2022.2-SP6.4, Build 146967, Jan 31 01:39 2024
#Install: E:\PDS\PDS_2022.2-SP6.4\bin
#Application name: pds.exe
#OS: Windows 10 10.0.19045
#Hostname: DESKTOP-9A06313
#Generated by Fabric Compiler(version 2022.2-SP6.4 build 146967) at Sun Apr 26 18:19:26 2026

#The following design files were local or imported into the project:
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/fifo/ipm_distributed_sdpram_v1_2_distributed_fifo.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_v1_2.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ipm_distributed_sdpram_v1_2.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_controller.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_cpld_tx_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_mrd_tx_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_mwr_tx_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_ram/ips2l_pcie_dma_ram.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ipm2l_sdpram_v1_1_ips2l_pcie_dma_ram.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ips2l_pcie_dma_ram_Reset_Value.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_rd_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_rx_cpld_wr_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_rx_mwr_wr_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_rx_top.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tlp_rcv.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tlp_tx_mux.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tx_cpld_rd_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tx_mwr_rd_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tx_top.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_wr_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_reg.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/arbiter.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar_addr.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar_rd.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar_wr.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_register_rd.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_register_wr.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/priority_encoder.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/top.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/pango_pcie_top.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/pcie_fifo.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/cmos_capture.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/i2c_dir.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/ov5640.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/ov5640_cdc.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/ov5640_i2c_rgb565_cfg.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_ddr/ov5640_ddr.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_ddr/ov5640_ddr_w.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_ddr/ov5640_ddr_w_ctrl.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_ddr/ov5640_ddr_w_en.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_reg.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_top.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/pipe_cdc.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/dma/axi_dma_write.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/dma/stream_pipe.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/axi_to_axi_lite.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/msi_arbiter.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_add.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_conv.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_in_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_in_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_in_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_in_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_mul.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_weight.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv/scale_mul.v
#C:/Users/ColorStripes/Desktop/111/sources_1/common/spram.v
#C:/Users/ColorStripes/Desktop/111/sources_1/common/fifo_ram.v
#C:/Users/ColorStripes/Desktop/111/sources_1/common/sync_fifo.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_conv.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_in_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_in_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_in_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_in_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_mul.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_out_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_out_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_out_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_para_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_weight.v
#C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_add.v
#C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_in_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_in_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_in_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_in_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_maxpool.v
#C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_in_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_in_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_in_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_para_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_out_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_out_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_out_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/common/scale_mul_unsign.v
#C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_in_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_in_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_in_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_in_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_in_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_in_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/out_buf/out_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/out_buf/out_buf_ctrl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/out_buf/out_buf_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/reg/axi_lite_interdace.v
#C:/Users/ColorStripes/Desktop/111/sources_1/reg/axi_lite_reg.v
#C:/Users/ColorStripes/Desktop/111/sources_1/reg/calculate_reg.v
#C:/Users/ColorStripes/Desktop/111/sources_1/reg/defines.v
#C:/Users/ColorStripes/Desktop/111/sources_1/npu_top/config.v
#C:/Users/ColorStripes/Desktop/111/sources_1/npu_top/npu_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/in_cat_switch.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/in_conv_switch.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/in_data_switch.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/in_switch_main.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/in_switch_main0.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/in_switch_main1.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/out_add_switch.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/out_conv_switch.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/out_data_switch.v
#C:/Users/ColorStripes/Desktop/111/sources_1/para/in_weight_switch.v
#C:/Users/ColorStripes/Desktop/111/sources_1/out_buf/out_switch.v
#C:/Users/ColorStripes/Desktop/111/sources_1/pcie2npu/instruction_buf.v
#C:/Users/ColorStripes/Desktop/111/sources_1/pcie2npu/npu_ctl.v
#C:/Users/ColorStripes/Desktop/111/sources_1/pcie2npu/pcie_npu.v
#C:/Users/ColorStripes/Desktop/111/sources_1/common/sync_fifo_replay.v
#C:/Users/ColorStripes/Desktop/111/sources_1/npu_cdc_top.v
#C:/Users/ColorStripes/Desktop/111/sources_1/common/pipe.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/cdc_cmd_channel.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/cdc_data_channel.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/npu_to_core_cdc_bridge.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axis_async_fifo.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar_7x3.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/dma/axi_dma.v
#C:/Users/ColorStripes/Desktop/111/pcie_dma/dma/axi_dma_read.v
#C:/Users/ColorStripes/Desktop/111/sources_1/common/fifo_ram_D.v
#C:/Users/ColorStripes/Desktop/111/sources_1/common/sync_fifo_D.v
#E:/FPGA/pcie/ipcore/pcie_test/pcie_test.idf
#E:/FPGA/pcie/ipcore/pcie_tx_fifo/pcie_tx_fifo.idf
#E:/FPGA/pcie/ipcore/pcie_rx_fifo/pcie_rx_fifo.idf
#E:/FPGA/pcie/ipcore/ddr3/ddr3.idf
#E:/FPGA/pcie/ipcore/ddr_fifo16_r/ddr_fifo16_r.idf
#E:/FPGA/pcie/ipcore/ddr_fifo16_w/ddr_fifo16_w.idf
#E:/FPGA/pcie/ipcore/ov5640_ddr_fifo_DRM/ov5640_ddr_fifo_DRM.idf
#E:/FPGA/pcie/ipcore/ov5640_ddr_fifo/ov5640_ddr_fifo.idf
#E:/FPGA/pcie/ipcore/ov5640_clk/ov5640_clk.idf
#E:/FPGA/pcie/ipcore/ins_cdc/ins_cdc.idf
#E:/FPGA/pcie/ipcore/ov5640_cdc_fifo_D/ov5640_cdc_fifo_D.idf
#E:/FPGA/pcie/source/ov5640.fdc
#E:/FPGA/pcie/source/ddr3.fdc
#E:/FPGA/pcie/source/pcie.fdc
#E:/FPGA/pcie/device_map/pango_pcie_top.pcf

#Copy design files:
#No file

set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484

add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/fifo/ipm_distributed_sdpram_v1_2_distributed_fifo.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_v1_2.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ipm_distributed_sdpram_v1_2.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_controller.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_cpld_tx_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_mrd_tx_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_mwr_tx_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_ram/ips2l_pcie_dma_ram.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ipm2l_sdpram_v1_1_ips2l_pcie_dma_ram.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ips2l_pcie_dma_ram_Reset_Value.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_rd_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_rx_cpld_wr_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_rx_mwr_wr_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_rx_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tlp_rcv.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tlp_tx_mux.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tx_cpld_rd_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tx_mwr_rd_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_tx_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_dma_wr_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/ips2l_pcie_reg.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/arbiter.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar_addr.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar_rd.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar_wr.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_register_rd.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_register_wr.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/priority_encoder.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/top.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/pango_pcie_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/pcie_dma_ctrl/pcie_fifo.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/cmos_capture.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/i2c_dir.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/ov5640.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/ov5640_cdc.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640/ov5640_i2c_rgb565_cfg.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_ddr/ov5640_ddr.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_ddr/ov5640_ddr_w.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_ddr/ov5640_ddr_w_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_ddr/ov5640_ddr_w_en.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_reg.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/ov5640_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/pipe_cdc.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/dma/axi_dma_write.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/dma/stream_pipe.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/ov5640/axi_to_axi_lite.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/msi_arbiter.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_add.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_conv.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_in_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_in_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_in_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_in_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_mul.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/conv_weight.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv/scale_mul.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/common/spram.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/common/fifo_ram.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/common/sync_fifo.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_conv.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_in_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_in_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_in_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_in_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_mul.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_out_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_out_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_out_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_para_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_weight.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/conv11_16/conv11_add.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_in_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_in_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_in_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_in_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_maxpool.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/sppf/sppf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_in_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_in_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_in_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_add_para_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_out_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_out_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/cat_add/cat_out_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/common/scale_mul_unsign.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_in_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_in_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_in_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/upsample/upsample_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_in_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_in_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_in_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/focus/focus_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/out_buf/out_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/out_buf/out_buf_ctrl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/out_buf/out_buf_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/reg/axi_lite_interdace.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/reg/axi_lite_reg.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/reg/calculate_reg.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/reg/defines.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/npu_top/config.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/npu_top/npu_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/in_cat_switch.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/in_conv_switch.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/in_data_switch.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/in_switch_main.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/in_switch_main0.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/in_switch_main1.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/out_add_switch.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/out_conv_switch.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/out_data_switch.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/para/in_weight_switch.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/out_buf/out_switch.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/pcie2npu/instruction_buf.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/pcie2npu/npu_ctl.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/pcie2npu/pcie_npu.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/common/sync_fifo_replay.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/npu_cdc_top.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/common/pipe.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/cdc_cmd_channel.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/cdc_data_channel.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/npu_to_core_cdc_bridge.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axis_async_fifo.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/axi_crossbar/axi_crossbar_7x3.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/dma/axi_dma.v}
add_design {C:/Users/ColorStripes/Desktop/111/pcie_dma/dma/axi_dma_read.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/common/fifo_ram_D.v}
add_design {C:/Users/ColorStripes/Desktop/111/sources_1/common/sync_fifo_D.v}
add_design {ipcore/pcie_test/pcie_test.idf}
add_design {ipcore/pcie_tx_fifo/pcie_tx_fifo.idf}
add_design {ipcore/pcie_rx_fifo/pcie_rx_fifo.idf}
add_design {ipcore/ddr3/ddr3.idf}
add_design {ipcore/ddr_fifo16_r/ddr_fifo16_r.idf}
add_design {ipcore/ddr_fifo16_w/ddr_fifo16_w.idf}
add_design {ipcore/ov5640_ddr_fifo_DRM/ov5640_ddr_fifo_DRM.idf}
add_design {ipcore/ov5640_ddr_fifo/ov5640_ddr_fifo.idf}
add_design {ipcore/ov5640_clk/ov5640_clk.idf}
add_design {ipcore/ins_cdc/ins_cdc.idf}
add_design {ipcore/ov5640_cdc_fifo_D/ov5640_cdc_fifo_D.idf}
 
set_global_include {C:/Users/ColorStripes/Desktop/111/sources_1/npu_top/config.v} true

add_constraint {source/ov5640.fdc}
add_constraint {source/ddr3.fdc}
add_constraint {source/pcie.fdc}
add_constraint {device_map/pango_pcie_top.pcf}
 
compile -top_module top

synthesize -ads -selected_syn_tool_opt 2 

dev_map 
