// Auto-generated by export_npy.py
double quant_scale = 0.00391965;
int quant_zero = 0;

double nms_scale[3] = { 0.085316672921180725, 0.084871567785739899, 0.089666269719600677 };
double nms_zero[3]  = { 138, 153, 172 };

int anchor_w[9] = { 25, 34, 44, 40, 48, 65, 148, 219, 315 };
int anchor_h[9] = { 14, 20, 21, 25, 29, 36, 32, 45, 57 };
double anchor_w_0[3] = { 4.625, 6.84375, 9.84375 };
double anchor_h_0[3] = { 1, 1.40625, 1.78125 };
double anchor_w_1[3] = { 2.5, 3, 4.0625 };
double anchor_h_1[3] = { 1.5625, 1.8125, 2.25 };
double anchor_w_2[3] = { 3.125, 4.25, 5.5 };
double anchor_h_2[3] = { 1.75, 2.5, 2.625 };
